export const EVENTS = {
  CONNECTION: 'connection',
  CLIENT: {
    CREATE_ROOM: 'CREATE_ROOM',
    JOIN_ROOM: 'JOIN_ROOM',
    SEND_ROOM_MESSAGE: 'SEND_ROOM_MESSAGE'
  },
  SERVER: {
    ROOMS: 'ROOMS',
    JOINED_ROOM: 'JOINED_ROOM',
    ROOM_MESSAGE: 'ROOM_MESSAGE'
  }
};
